function_declarations:
  - name: swipe_left
    description: left
    parameters:
      type: object
      properties:
        observation:
          type: string
          description: Was the previous action done correctly? What do see now that is relevant to your next course of action and was previous step successfully completed and why next step is swipe_left
      required:
        - observation

  - name: swipe_right
    description: right
    parameters:
      type: object
      properties:
        observation:
          type: string
          description: Was the previous action done correctly? What do see now that is relevant to your next course of action and was previous step successfully completed and why next step is swipe_right
      required:
        - observation

  - name: swipe_up
    description: swipes up, which will show upper parts of the screen - opposite behavior than scroll up
    parameters:
      type: object
      properties:
        observation:
          type: string
          description: Was the previous action done correctly? What do see now that is relevant to your next course of action and was previous step successfully completed and why next step is swipe_up
      required:
        - observation

  - name: swipe_down
    description: swipes down, which will show upper parts of the screen - opposite behavior than scroll down
    parameters:
      type: object
      properties:
        observation:
          type: string
          description: Was the previous action done correctly? What do see now that is relevant to your next course of action and was previous step successfully completed and why next step is swipe_down
      required:
        - observation

  - name: navigate_back
    description: back
    parameters:
      type: object
      properties:
        observation:
          type: string
          description: Was the previous action done correctly? What do see now that is relevant to your next course of action and was previous step successfully completed and why next step is navigate_back
      required:
        - observation

  - name: minimize_app
    description: minimize
    parameters:
      type: object
      properties:
        observation:
          type: string
          description: Was the previous action done correctly? What do see now that is relevant to your next course of action and was previous step successfully completed and why next step is minimize_app
      required:
        - observation
  - name: volume_up
    description: increase volume
    parameters:
      type: object
      properties:
        observation:
          type: string
          description: Was the previous action done correctly? What do see now that is relevant to your next course of action and was previous step successfully completed and why next step is volume_up
      required:
        - observation

  - name: volume_down
    description: decrease volume
    parameters:
      type: object
      properties:
        observation:
          type: string
          description: Was the previous action done correctly? What do see now that is relevant to your next course of action and was previous step successfully completed and why next step is volume_down
      required:
        - observation
