function_declarations:
  - name: screenshot
    description: Take a full screenshot of the screen. This screenshot will be used to plan our steps.
    parameters:
      type: object
      properties:
        observation:
          type: string
          description: Was the previous action done correctly? What do u see now that is relevant to your next course of action and was previous step successfully completed and why next step is a screenshot.
      required:
        - observation

  - name: type_text
    description: Type the provided text in some input box or typable area.
    parameters:
      type: object
      properties:
        text:
          type: string
          description: Text to type.
        observation:
          type: string
          description: Was the previous action done correctly? What do u see now that is relevant to your next course of action and was previous step successfully completed and why next step is a type_text
      required:
        - text
        - observation

  # - name: click_at_a_point
  #   description: Click at specific coordinates, usually the center of a previously found UI element.
  #   parameters:
  #     type: object
  #     properties:
  #       x:
  #         type: integer
  #         description: X-coordinate.
  #       y:
  #         type: integer
  #         description: Y-coordinate.
  #       observation:
  #         type: string
  #         description: Was the previous action done correctly? What do u see now that is relevant to your next course of action and was previous step successfully completed and why next step is a click at a point
  #     required:
  #       - x
  #       - y
  #       - observation

  - name: find_element_and_click
    description: Find the coordinates of an element on the screen using a prompt. In the prompt, specify which section of the screen.
    parameters:
      type: object
      properties:
        prompt:
          type: string
          description: e.g., 'Safari icon in the dock or on screen'.
        observation:
          type: string
          description: Was the previous action done correctly? What do u see now that is relevant to your next course of action and was previous step successfully completed and why next step is to find coordinates of an ui element
      required:
        - prompt
        - observation

  - name: task_finished
    description: Last step.
    parameters:
      type: object
      properties:
        reason:
          type: string
          description: Why you say so.
        observation:
          type: string
          description: Was the previous action done correctly? What do u see now that is relevant to your next course of action and was previous step successfully completed
      required:
        - reason
        - observation